# Generated by Django 5.1.1 on 2025-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="users/%Y/%m/%d/"),
        ),
    ]
