# Generated by Django 5.1.1 on 2025-06-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
