# Generated by Django 5.1.1 on 2025-06-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_category_icon"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"parent__isnull": False},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="category.category",
            ),
        ),
    ]
